name: Backend CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust to your Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv  # Create a virtual environment
          source venv/bin/activate  # Activate the virtual environment
          pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: |
          source venv/bin/activate  # Activate virtual environment
          pytest  # Run tests

      # Step 5: Lint code using flake8
      - name: Lint code
        run: |
          source venv/bin/activate  # Activate virtual environment
          pip install flake8  # Install flake8 if it's not in requirements.txt
          flake8 .  # Run flake8 linter
          flake8 --exclude venv/*  # Ignore the venv directory

      # Step 6: Build application (optional)
      - name: Build application
        run: |
          source venv/bin/activate  # Activate virtual environment
          echo "Building the application"
